version: "3.6"
services:
  hasura:
    image: hasura/graphql-engine:v1.2.0-beta.3
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:5432/db?user=postgres&password=&sslmode=disable
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      AUTH_SERVER_URL: "http://host.docker.internal:1111/graphql"
      HASURA_GRAPHQL_LOG_LEVEL: "debug"

  postgres:
    image: postgres:10.5
    ports:
      - "54321:5432"

    environment:
      POSTGRES_DB: db
