version: "3.6"
services:
  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:5432/db?user=postgres&password=&sslmode=disable
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"

  postgres:
    image: postgres:10.5
    ports:
      - "54321:5432"

    environment:
      POSTGRES_DB: db
